test-e2e/cypress/e2e/features/MOB_Feature/steps.cy.js
=> [MOB-26] BE - Cucumber over Cypress Setup (FIX)

test-e2e/cypress/e2e/features/MOB_Feature/steps.cy.js
=> [MOB-26] BE - Cucumber over Cypress Setup ( FIX 3 )

src/infraestructure/db/schema/event.schema.ts, src/infraestructure/dtos/event.dto.ts, test/jest-component/event/get-events.spec.ts, test/mocks/dtos/event.ts
=> [MOB-52] GET events - Unnecessary data in the response

src/infraestructure/dtos/event.dto.ts
=> [MOB-55] Tag field appears in the response when empty

src/infraestructure/dtos/event.dto.ts
=> [MOB-55] Fixing event schema

.github/workflows/WhenMainChanges.yml
=> [MOB-54] BE - Postman test pipe Setup

.github/workflows/WhenMainChanges.yml
=> [MOB-54] BE - Postman test pipe Setup ( patch ADD SLACK )

.github/workflows/WhenMainChanges.yml
=> [MOB-54] BE - Postman test pipe Setup ( patch ADD SLACK  Fix1)

.github/workflows/WhenMainChanges.yml
=> [MOB-54] BE - Postman test pipe Setup ( patch ADD SLACK Fix2)

.gitignore, src/infraestructure/db/repositories/event.repository.ts, src/infraestructure/db/services/index.ts, src/infraestructure/db/services/validate-mapped-object.ts, src/infraestructure/dtos/event.dto.ts, test/jest-unit/infraestrcture/db/services/validated-mapped-object.spec.ts
=> [MOB-57] - Fixing swagger for GET /events

.github/workflows/WhenMainChanges.yml
=> [MOB-38] Deploy in Oracle

package.json, src/infrastructure/http/dtos/create-event.dto.ts, src/main.ts, test/jest-component/jest-component.config.json
Add this in .env:
```
DNS_NAME = https://qa.esmorga.canarte.org
```
=> [MOB-71] BE - Update Swagger with json link and ApiProperty

.github/workflows/WhenMainChanges.yml, .github/workflows/WhenPR.yml
=> [MOB-38] - BE - Create GitHubActions & Basic Setup - Change QA Server

src/infrastructure/http/dtos/create-event.dto.ts, test/jest-unit/infrastructure/http/dtos/create-event.dto.spec.ts
Create events with expected validate eventTypes: `Party, Sport, Food, Charity, Games`
```
--data '{
"eventName": "Fest Games",
"eventDate": "2025-03-08T10:05:30.915Z",
"description": "Hello World",
"eventType": "Games",
"imageUrl": "img.url",
"location": {
"lat": 43.35525182148881,
"long": -8.41937931298951,
"name": "A Coruña"
},
"tags": [
"Meal",
"Music"
]
}'
```
Check eventType is returned correctly
```
```
=> [MOB-74] POST Events - eventType value is handled in UpperCase

migrations/1718793301029_update_password_user_login_fow.js, migrations/1718793301029_update_password_user_login_fow.ts
Check the 3 users:
```
esmorga.test.01@yopmail.com - Password01 - ADMIN
esmorga.test.02@yopmail.com - Password02 - ADMIN
esmorga.test.03@yopmail.com - Password03 - USER
```
```
curl --location 'http://localhost:3000/v1/account/login' \
--data-raw '{
"email": "esmorga.test.03@yopmail.com",
"password": "Password03"
}'
```
=> [MOB-76] BE - Align users password added during login flow development

.github/workflows/WhenPR.yml
=> [MOB-38] BE - Create GitHubActions & Basic Setup - ADD Just run test if code changes

migrations/1719473131171_add_users.js, migrations/1719473131171_add_users.ts
Check that the pending migration appears:
```
npx mongo-migrate status
```
Execute the migration to add users to db (check the status and the mongo db to see the new users added):
```
npx mongo-migrate up
```
Execute the down command to make all the checks (check the status and the mongo db to see the users deleted):
```
npx mongo-migrate down -l
```
Finally leave the migration up.
=> [MOB-77] BE - Add test users to DB

src/infrastructure/http/dtos/create-event.dto.ts, test/jest-unit/infrastructure/http/dtos/create-event.dto.spec.ts
Check that when you create and event with empty location name or description the expected error appears:
```
--data '{
"eventName": "TestingPost",
"eventDate": "2024-08-05T10:30:30.915Z",
"description": "Hello World",
"eventType": "Party",
"imageUrl": "img.url",
"location": {
"lat": 43.35525182148881,
"long": -8.41937931298951,
"name": "A Coruña"
},
"tags": [
"Meal",
"Music"
]
}'
```
=> [MOB-78] 🐛 BE - POST Events API - No 'some inputs are missing' error shown

.github/pull_request_template.md, src/infrastructure/http/dtos/account-register.dto.ts
Example curl:
```
--data-raw '{
"name": "Carlos",
"lastName": "Valderrama",
"password": "invalidPass",
"email": "ozounalocal8@yopmail.com"
}'
```
=> [MOB-81] POST Register API - Incomplete error message for password validation

src/application/handler/account/login.service.ts, src/infrastructure/http/dtos/account-login.dto.ts
Example curls:
```
--data-raw '{
"name": "Carlos",
"lastName": "Valderrama",
"password": "SuperSecret1!",
"email": "OZUNAlocal8@yopmail.com"
}'
```
```
curl --location 'http://localhost:3000/v1/account/login' \
--data-raw '{
"email": "OZUNAlocal8@yopmail.com",
"password": "SuperSecret1!"
}'
```
=> [MOB-83] POST Login API - Email not case insensitive

src/infrastructure/http/dtos/create-event.dto.ts, test/jest-unit/infrastructure/http/dtos/create-event.dto.spec.ts
Example curl:
```
--data '{
"eventName": "Fest Games",
"eventDate": "2025-03-08T10:05:30.915Z",
"description": "Hello World",
"eventType": "Games",
"imageUrl": "img.url",
"location": {
"lat": 43.35525182148881,
"long": -8.41937931298951,
"name": "A Coruña"
},
"tags": [
"Meal",
"Music"
]
}'
```
=> [MOB-62] POST Events API - Improve validation in case invalid information

src/infrastructure/http/dtos/account-register.dto.ts
Example curl:
```
--data-raw '{
"name": "Aless",
"lastName": "Dosil",
"password": "Test123456'\''",
"email": "aless5@yopmail.com"
}'
```
=> [MOB-84] POST Register API - Special characters not treated as special characters

src/infrastructure/http/dtos/create-event.dto.ts, test/jest-unit/infrastructure/http/dtos/create-event.dto.spec.ts
Example curl:
```
--data '{
"eventName": "MobgenFest",
"eventDate": "2025-03-08T10:05:30.915Z",
"description": "AM",
"eventType": "Party",
"imageUrl": "14FAFBRHz9Y",
"location": {
"name": "",
"lat": 43,
"long": -8
},
"tags": [
"Meal",
"Music"
]
}'
```
Documentation &rarr; ticket linked to POST `/events` related stories
=> [MOB-112] Changing error message in createEventDto description

src/infrastructure/http/dtos/account-register.dto.ts
Curl:
```
--data-raw '{
"name": "Aless",
"lastName": "Dosil",
"password": "Test123456'\''",
"email": "aless@yopmail.c"
}'
```
=> [MOB-115] Register API - The error message does not help to understand the problem

src/domain/services/validate-login-credentials.ts
Example curl (use a pre-created user with old password algorithm):
```
curl --location 'http://localhost:3000/v1/account/login' \
--data-raw '{
"email": "esmorga.test.02@yopmail.com",
"password": "Password02"
}'
```
=> [MOB-117]  Change password hash strategy - 500 when login

test/scripts/lib/GitHelper.js
=> MOB[79] - FIX -  The objetive Branch in in the second line of the log

test/scripts/lib/GitHelper.js
=> [MOB-39] -FIX - remove a LOOP 

test/scripts/features-tool.js, test/scripts/lib/GitHelper.js
=> [MOB-79] -FIX -  Loop until ( = main )

test/scripts/features-tool.js, test/scripts/lib/GitHelper.js
=> [MOB-79] -FIX - Remove get branch from GH VAR

test/scripts/features-tool.js, test/scripts/lib/GitHelper.js
=> [MOB-79] - FIX - ADD LIMIT 20

package.json, src/config/execute-migrations.ts
Change env-var value for `NODE_ENV` to do not see unncessary information related to not found script to execute migrations during start up process
=> [MOB-120] Improve start up process for pipes

.github/tmp/branch.txt, src/domain/services/generate-mail.ts
Example curl:
```
--data-raw '{
"name": "Carlos",
"lastName": "Valderrama",
"password": "SuperSecret1!",
"email": "ozounalocal29@yopmail.com"
}'
```
=> [MOB-156] Register - Fix Subject email

.github/tmp/branch.txt, src/application/handler/account/register.service.ts
Example curl:
```
--data-raw '{
"name": "Carlos",
"lastName": "Valderrama",
"password": "SuperSecret1!",
"email": "ozounalocal29@yopmail.com"
}'
```
=> [MOB-155] Register - Too long response

.github/tmp/branch.txt, test/cypress-e2e/cypress/e2e/features/MOB_Feature/steps.cy.js, test/cypress-e2e/cypress/e2e/pages/account/api_login.js, test/cypress-e2e/cypress/e2e/pages/account/password/api_forgot_password.js, test/cypress-e2e/cypress/e2e/pages/account/password/api_password_update.js, test/cypress-e2e/cypress/e2e/pages/api_basic.js, test/scripts/features-tool.js
=> [MOB-123] ADD  TEST MOB-TC-169

.github/actions/runUnitTests/action.yaml, .github/tmp/branch.txt
=> Need to know naming

.github/tmp/branch.txt, migrations/prod/1726137333274_add_mobile_makers_admin.js, migrations/prod/1726137333274_add_mobile_makers_admin.ts, migrations_prod.json, src/config/execute-migrations.ts
Use `NODE_ENV = PROD` and use your own db url, you should not have access to prod url
=> [MOB-167] -  Add an admin user to PROD env

.github/actions/runComponentTests/action.yaml, .github/actions/runE2ETests/action.yaml, .github/actions/runUnitTests/action.yaml, .github/tmp/branch.txt
=> [MOB-79] - Upload test report just on Merge

.github/actions/Deploy/action.yaml, .github/tmp/branch.txt, .github/workflows/DeployToProd.yml, .github/workflows/WhenMainChanges.yml, .github/workflows/WhenReleaseChanges.yml
=> [MOB-165] Create Deploy Workflow & Rename Deploy Action

.github/tmp/branch.txt, test/scripts/features-tool.js, test/scripts/lib/Aio.js, test/scripts/lib/Features.js
https://mobilemakers.atlassian.net/browse/MOB-165
=> [MOB-165] Change how we find US in branch name

.github/tmp/branch.txt, .github/workflows/scripts/DeployToEnv.py
=> [MOB-148] Add env variables to BE pipelines

.github/tmp/branch.txt, .github/workflows/WhenReleaseChanges.yml, .github/workflows/scripts/CheckEnv.py, .github/workflows/scripts/DeployToEnv.py
=> [MOB-148] FIX Naming & fix ssh

.github/tmp/branch.txt, .github/workflows/Deploy.yml, .github/workflows/scripts/DeployToEnv.py
=> [MOB-148] Disable Slack on Deploy

.github/tmp/branch.txt, .github/workflows/Deploy.yml, .github/workflows/WhenPR.yml
=> [MOB-148] FIX SSHRSA

.github/tmp/branch.txt, .github/workflows/Deploy.yml, .github/workflows/scripts/DeployToEnv.py
https://mobilemakers.atlassian.net/browse/MOB-149
=> [MOB-149] Define BE PROD deployment strategy

.github/tmp/branch.txt, .github/workflows/Deploy.yml, .github/workflows/DispatchDeploy.yml
=> [MOB-149] Jira Automation to Deploy

.github/actions/pushOasFile/action.yaml, .github/tmp/branch.txt, .github/workflows/CheckEnv.yml, .github/workflows/Deploy.yml, .github/workflows/DispatchDeploy.yml, .github/workflows/WhenPR.yml
=> [MOB-149] ADD Branch to release & When execute PUSH OAS

.github/tmp/branch.txt, .github/workflows/Deploy.yml
=> [MOB-149] ADD $github.event.client_payload.env 

.github/tmp/branch.txt, .github/workflows/CreateRelease.yml
=> [MOB-149] Fix usKey description

.github/tmp/branch.txt, .github/workflows/scripts/CheckEnv.py
=> [MOB-149] Clean Code on CheckEnv.py

.github/tmp/branch.txt, migrations/1726575490719_update_user_status_to_active.ts
=> [MOB-132] Fix status users to active migration

.github/tmp/branch.txt, .github/workflows/Deploy.yml, .github/workflows/WhenPR.yml, .github/workflows/scripts/CheckEnv.py, .github/workflows/scripts/DeployToEnv.py
=> [FIX] ADD " on deploy to ENV 

.github/tmp/branch.txt, .github/workflows/scripts/DeployToEnv.py, test/scripts/features-tool.js, test/scripts/lib/Aio.js, test/scripts/lib/Features.js
=> [Bugfix] Add retry to aio api

.github/tmp/branch.txt, .github/workflows/scripts/DeployToEnv.py
=> [PIPE] Return a 503 response during an ongoing deployment.

.github/actions/runPostmanTests/action.yaml, .github/tmp/branch.txt, .github/workflows/WhenMainChanges.yml, .github/workflows/WhenPR.yml, test/cypress-e2e/cypress/e2e/features/MOB_Feature/steps.cy.js, test/cypress-e2e/cypress/e2e/pages/account/api_login.js, test/scripts/lib/Aio.js
=>  [MOB-166] ADD E2E TESTS

.github/tmp/branch.txt, test/jest-component/features/steps/reusable-steps.ts, test/jest-component/instruments/swagger-things.ts
=> [MOB-123] Fix not mark as automated

.github/tmp/branch.txt, .vscode/launch.json, package-lock.json, package.json, src/app.module.ts, src/config/env-validation.ts, src/infrastructure/http/controllers/account.controller.ts, src/infrastructure/http/errors/exception-filter.ts, src/main.ts, test/jest-component/jest-cucumber-setup.ts
=> [MOB-189] Endpoints Rate limit

.github/tmp/branch.txt, .github/workflows/WhenMainChanges.yml
=> [MOB-189] Disable Postman tests

.github/actions/runService/action.yaml, .github/tmp/branch.txt, .github/workflows/WhenMainChanges.yml, test/cypress-e2e/cypress/e2e/lib/api_1secmail.js
=> Need to test on merge

.github/actions/runPostmanTests/action.yaml, .github/tmp/branch.txt, .github/workflows/WhenMainChanges.yml, test/cypress-e2e/cypress/e2e/lib/all_mail_apis.js, test/cypress-e2e/cypress/e2e/lib/api_1secmail.js, test/cypress-e2e/cypress/e2e/lib/api_maildrop.js, test/cypress-e2e/cypress/e2e/pages/account/password/api_forgot_password.js, test/mocks/db/event.ts, test/mocks/dtos/event.ts
https://mobilemakers.atlassian.net/browse/MOB-209
##
Remove password recovery related in  MOB-CY-149 ( CY for MOB-209 )
=> Implement Redundant Email Services for Automated Testing

.github/tmp/branch.txt, migrations/1742206181002_add_new_events_with_true_future_date.js, migrations/1742206181002_add_new_events_with_true_future_date.ts, test/cypress-e2e/cypress.config.js, test/cypress-e2e/cypress/e2e/features/MOB_Feature/steps.cy.js, test/cypress-e2e/cypress/e2e/lib/all_mail_apis.js, test/cypress-e2e/cypress/e2e/lib/api_maildrop.js, test/cypress-e2e/cypress/e2e/lib/api_mailesmorga.js, test/cypress-e2e/cypress/e2e/pages/account/api_activate.js, test/cypress-e2e/cypress/e2e/pages/account/api_register.js, test/cypress-e2e/cypress/e2e/pages/account/password/api_forgot_password.js, test/cypress-e2e/cypress/e2e/pages/account/password/api_password_update.js, test/jest-component/features/steps/account/activate-account-steps.ts, test/jest-unit/infrastructure/http/dtos/create-event.dto.spec.ts, test/mocks/dtos/create-event.ts, test/mocks/dtos/update-event.ts
=> FIX all TEST & ADD new Migration to solve Date problems

.github/tmp/branch.txt, .github/workflows/WhenMainChanges.yml
=> [MOB-173-2] Disable postman tests

.github/tmp/branch.txt, .github/workflows/WhenMainChanges.yml
=> [MOB-173-3] Enable postman and E2E tests

.github/actions/runE2ETests/action.yaml, .github/tmp/branch.txt, .github/workflows/WhenMainChanges.yml, .github/workflows/WhenReleaseChanges.yml, migrations/1751549010877_add_e2e_esmorga_mail_user.js, migrations/1751549010877_add_e2e_esmorga_mail_user.ts, test/cypress-e2e/cypress/e2e/lib/api_mailesmorga.js, test/cypress-e2e/cypress/e2e/pages/account/api_login.js
=> Add new user @esmorga.canarte.org to fix cypress E2E

.github/tmp/branch.txt, .github/workflows/CreateRelease.yml, .github/workflows/Deploy.yml, README.md
=> BE Pipe Deploy to PROD Fix
